<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="FUJINLUAN" name="meibanStaffChannel.delSpecialStaffsAndResult" tests="8" failures="2"
           timestamp="5 Jan 2018 08:22:55 GMT" time="0.868" errors="0">
    <testcase name="delSpecialStaffsAndResult6" time="0.020" classname="meibanStaffChannel.delSpecialStaffsAndResult">
        <failure type="java.lang.AssertionError" message="10500 StateMessage:System error">
            <![CDATA[java.lang.AssertionError: 10500 StateMessage:System error
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.assertNotEquals(Assert.java:930)
	at meibanStaffChannel.delSpecialStaffsAndResult.delSpecialStaffsAndResult6(delSpecialStaffsAndResult.java:114)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
        </failure>
    </testcase> <!-- delSpecialStaffsAndResult6 -->
    <testcase name="delSpecialStaffsAndResult5" time="0.148" classname="meibanStaffChannel.delSpecialStaffsAndResult"/>
    <testcase name="delSpecialStaffsAndResult7" time="0.020" classname="meibanStaffChannel.delSpecialStaffsAndResult"/>
    <testcase name="delSpecialStaffsAndResult2" time="0.168" classname="meibanStaffChannel.delSpecialStaffsAndResult">
        <failure type="java.lang.AssertionError" message="0 StateMessage:OK">
            <![CDATA[java.lang.AssertionError: 0 StateMessage:OK
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.assertNotEquals(Assert.java:930)
	at meibanStaffChannel.delSpecialStaffsAndResult.delSpecialStaffsAndResult2(delSpecialStaffsAndResult.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
        </failure>
    </testcase> <!-- delSpecialStaffsAndResult2 -->
    <testcase name="delSpecialStaffsAndResult8" time="0.172" classname="meibanStaffChannel.delSpecialStaffsAndResult"/>
    <testcase name="delSpecialStaffsAndResult1" time="0.294" classname="meibanStaffChannel.delSpecialStaffsAndResult"/>
    <testcase name="delSpecialStaffsAndResult3" time="0.024" classname="meibanStaffChannel.delSpecialStaffsAndResult"/>
    <testcase name="delSpecialStaffsAndResult4" time="0.022" classname="meibanStaffChannel.delSpecialStaffsAndResult"/>
</testsuite> <!-- meibanStaffChannel.delSpecialStaffsAndResult -->
